Chunk status alert
Octol1ttle/FlightAssistant pull request #11
Opened 2024-03-16 14:03 UTC by zomabies

This PR add some feature for chunk status, as follow.

Indicate if current chunk is unloaded, use last ground height as reference.

Player will receive an alert when they fly into unloaded chunk after a certain amount of time.

It has 3 stages of alerts:
- In 1.25 seconds, alert sound and text is shown (advice color).
- By 3 seconds, text color changed to caution.
- After 5 seconds, duration color changed to warning, protection kicked in by pitching up by ~10 degrees.

2024-03-17 12:18 UTC, Octol1ttle requested changes

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/FAModMenuImpl.java
> +                        .build())
Normal warnings don't need a warning mode setting

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/alerts/nav/UnloadedChunkAlert.java
> +    private final AirDataComputer adc;
Should be `data`

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/alerts/nav/UnloadedChunkAlert.java
> +        return AlertSoundData.ifEnabled(FAConfig.computer().chunkStatusWarning, AlertSoundData.MASTER_CAUTION);
Alerts in red shouldn't be combined with the MASTER CAUTION sound (and CAUT doesn't seem appropriate for how dangerous flying in unloaded chunks can be)

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/alerts/nav/UnloadedChunkAlert.java
> +        HudComponent.drawHighlightedText(textRenderer, context, text, x + textWidth, y, chunkStatus.getIndicator(ChunkStatusLevel.WARNING), highlight);
The timer doesn't appear important to the user

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/autoflight/PitchController.java
> +        }
This instance of automatic pitch correction isn't mutually exclusive with autopilot pitch movement, which will lead to these systems fighting

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/autoflight/PitchController.java
> +            smoothSetPitch(FAMathHelper.toDegrees(MathHelper.atan2(chunkStatus.recoverVector.y, chunkStatus.recoverVector.x)), time.deltaTime);
Why calculate pitch from a vector if the vector is constant?

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
This computer seems overengineered, there's instances of data duplication across computers and unnecessary logic to compute the unloaded time which, as outlined previously, doesn't bring any value

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +            case ADVISORY -> FAConfig.indicator().advisoryColor;
The advisory color is to show things that the user needs to follow. Examples are ECAM actions, flight directors and target altitude/heading. It is not to be used for warnings

2024-03-17 12:18 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/indicators/AltitudeIndicator.java
> +            }
This should show a placeholder instead. similar to those displayed when an indicator failure occurs (see `renderFaulted`)

2024-03-19 11:21 UTC, Octol1ttle requested changes

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/autoflight/PitchController.java
> +            smoothSetPitch(chunkStatus.recoverPitch, time.deltaTime);
Make `VoidLevelComputer.OPTIMUM_ALTITUDE_PRESERVATION_PITCH` public and use it here

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/alerts/nav/UnloadedChunkAlert.java
> +
Unnecessary newline

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/alerts/nav/UnloadedChunkAlert.java
> +
Unnecessary newline

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +
Unnecessary newline

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/autoflight/PitchController.java
> +
Unnecessary newline

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +            if (!host.faulted.contains(time) && time.prevMillis != null) {
Don't inject `ComputerHost` here and remove the faulted check

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +        }
How does this differ from 
```java
        if (!data.isFlying()) {
            reset();
            return;
        }
```

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +        isLoaded = data.isCurrentChunkLoaded;
Data duplication, callers should use `data.isCurrentChunkLoaded` directly

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +    }
Overriden methods should come last

2024-03-19 11:21 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +    }
Callers should use `FAConfig.indicator().warningColor` directly

2024-03-20 18:44 UTC, zomabies commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +        }
There's no difference, but preferably it should only run once when stop flying.

2024-03-20 18:47 UTC, Octol1ttle commented on src/main/java/ru/octol1ttle/flightassistant/computers/safety/ChunkStatusComputer.java
> +        }
I think it's fine to always run it for sake of simplicity

2024-03-21 11:13 UTC, Octol1ttle approved these changes

2024-03-21 11:13 UTC, merged