Chinese localization
Octol1ttle/FlightAssistant pull request #22
Opened 2024-08-16 16:36 UTC by Baichuan-qiao

add "zh_cn.json"

2024-08-17 07:29 UTC, Octol1ttle requested changes

2024-08-17 07:29 UTC, Octol1ttle commented on src/main/resources/assets/flightassistant/lang/zh_cn.json
I no longer use JSON for language files. I also noticed there are a few strings that are missing or out of date, please check out the latest language file at https://github.com/Octol1ttle/FlightAssistant/blob/dev/src/main/resources/assets/flightassistant/lang/en_us.yml and update your pull request accordingly.

2024-08-23 14:15 UTC, Baichuan-qiao commented on src/main/resources/assets/flightassistant/lang/zh_cn.json
I will complete it soon.

2024-08-23 15:00 UTC, Baichuan-qiao commented on src/main/resources/assets/flightassistant/lang/zh_cn.json
I have completed it.

2024-08-23 15:02 UTC, Baichuan-qiao commented
I have revised the original unreasonable translation and translated the new features.

2024-08-23 18:00 UTC, Octol1ttle approved these changes

2024-08-23 18:03 UTC, merged